# This config file is used by ros2_control
/exchange_station:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      exchange_arm_group_controller:
        type: joint_trajectory_controller/JointTrajectoryController


      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  exchange_arm_group_controller:
    ros__parameters:
      joints:
        - J1
        - J2
        - J3
        - J4
        - J5
        - J6
        - J7
      command_interfaces:
        - position
        - velocity
      state_interfaces:
        - position
        - velocity

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    exchange_arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

exchange_arm_group_controller:
  ros__parameters:
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
      - J7
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity